# Generated by Django 4.1.1 on 2023-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image_project_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
