# Generated by Django 4.1.1 on 2023-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
