# Generated by Django 4.1.1 on 2023-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_project_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotator',
            old_name='user',
            new_name='anotator',
        ),
        migrations.AddField(
            model_name='annotator',
            name='custom_anotator_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
