# Generated by Django 4.1.1 on 2023-03-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_user_annotator_anotator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotator',
            old_name='anotator',
            new_name='user',
        ),
    ]
