# Generated by Django 4.2 on 2023-05-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_anotator_annotator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotators',
            field=models.ManyToManyField(blank=True, to='main.annotator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.image'),
        ),
    ]
