# Generated by Django 4.2 on 2023-05-03 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_annotators_alter_project_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000000000000000000),
            preserve_default=False,
        ),
    ]
