# Generated by Django 4.2.1 on 2023-05-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_annotator_created_date_image_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='label',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.annotator')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image')),
            ],
        ),
    ]
