# Generated by Django 4.2 on 2023-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_annotator_custom_anotator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=5000000000),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='main.image'),
        ),
    ]
