# Generated by Django 4.2 on 2023-05-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_description_alter_project_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.image'),
        ),
    ]
