# Generated by Django 4.2 on 2023-05-09 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotator',
            name='bio',
        ),
        migrations.AddField(
            model_name='annotator',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
