# Generated by Django 4.2 on 2023-05-11 08:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_myannotators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annotations',
            new_name='Annotation',
        ),
        migrations.RenameModel(
            old_name='MyAnnotators',
            new_name='MyAnnotator',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000000),
            preserve_default=False,
        ),
    ]
